### ISSUE TITLE
Issue: Unable to view brief description of snippet in suggestion window. 

### ISSUE THREAD

**Issue by gopalagrawal** [snipsnapdev/snipsnap-vscode#12]
In the home page of this snippet, the demo shows a user getting snippet suggestions in which the titles are fully visible ... like so: 
![Capture](https://user-images.githubusercontent.com/703393/85360302-607eb700-b536-11ea-837b-9b98a45016d2.JPG)

But what I get is a partially visible title of the snippet making all the suggestion look the same (see figure below).   I am unable to widen this window or column or get rid of the detailed description column which reduces width of first title column.   Sure, I could scroll down each one and then get the details of the snippet in the right-side pane that shows the full snippet,  but the whole idea is that I should sort of know which one I need to scroll down to immediately by just viewing the brief titles.  Right now,  all my titles are seen only as **"react component ..."**. 
![Capture](https://user-images.githubusercontent.com/703393/85360537-02060880-b537-11ea-9efc-84d4cb75441e.JPG)

Hope this is addressed soon.  Perhaps some config setting to get rid of the detailed description in the left pane .... since that is already available in the right pane (so it is redundant). 

Environment::  Ubuntu 18.04  +  VS Code:  1.45.1

**Comment by BolotskyDev** [comment]
Answered in [here](https://github.com/snipsnapdev/snipsnap/issues/40), closing the issue. Thanks for reporting that, @gopalagrawal !
