### ISSUE TITLE
Error fetching snipsnap.code-snippets

### ISSUE THREAD

**Issue by ace3** [snipsnapdev/snipsnap-vscode#24]
i tried on clean project, but there is this error

`{"errors":[{"name":"SequelizeConnectionError","message":"could not open file \"global/pg_filenode.map\": Permission denied"}]}`

i think it's related to the server for fetching snippets ?

I'm using `v1.1.1` of the plugins.

**Comment by lnikell** [comment]
Thank you @ace3 for reporting the issue, it's fixed. Due to infrastructure updates, there some problems that were appeared for that particular project.
